spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workflow
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
server:
  error:
    include-stacktrace: never
